### ISSUE TITLE
Cocos creator integration with math wallet

### ISSUE THREAD

**Issue by hossainiir** [MediShares/MathWalletSDK-Android#1]
Hi, I'm working on a game in eos/telos blockchain.
I'm using cocos creator as game engine, I have integrated cc(cocos creator) with math wallet.
When I call login , the math wallet login page is showing, but when I enter my password and confirm the math wallet doesn't back to the game, and math wallet ask me to select a program to launch.
My problem is that how can I back to the game after login?

**Comment by hossainiir** [comment]
Hi I think I found the problem, this issue will happen when main activity inherited from AppActivity.
Now how can I use math wallet with an AppActivity class??

**Comment by guangxingmao** [comment]
> Hi I think I found the problem, this issue will happen when main activity inherited from AppActivity.
> Now how can I use math wallet with an AppActivity class??

hello,if you implementation(name: 'mathwalletlib-release', ext: 'aar') and regist RouterActivity, then you can perform the following operations:
   1. login 
         please setLoginUrl is null(required),it will back to the game and callBack Eos accountName and permission after confirm password. you can see this callback log:
       LogUtil.e(TAG, new JSONObject(params).toString());  
  
  2. custom action 
        setBinargs(required), invoke abi_json_to_bin ABI can get this binargs string.  

and if you have other problems ,welcome to leave your contact way like telegram.

**Comment by hossainiir** [comment]
This is my telegram id hossainiir

**Comment by guangxingmao** [comment]
> hossainiir

sorry, i can't send message to you in telegram by limited ,please add me , my telegram id maoguangxing.
